# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MsProjectList',
            fields=[
                ('project_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=256)),
                ('project_parent_id', models.CharField(blank=True, max_length=256, null=True)),
                ('project_svn_address', models.CharField(blank=True, max_length=256, null=True)),
                ('project_create_date', models.DateField(blank=True, null=True)),
                ('project_modify_date', models.DateField(blank=True, null=True)),
                ('project_sqr', models.CharField(blank=True, max_length=256, null=True)),
                ('project_status', models.CharField(blank=True, max_length=256, null=True)),
                ('project_remark', models.CharField(blank=True, max_length=256, null=True)),
                ('project_creator', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'ms_project_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MsProjectOtherinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=256, null=True)),
                ('other_name', models.CharField(blank=True, max_length=256, null=True)),
                ('other_remark', models.CharField(blank=True, max_length=256, null=True)),
                ('other_sqr', models.CharField(blank=True, max_length=256, null=True)),
                ('other_lx', models.CharField(blank=True, max_length=256, null=True)),
                ('other_sq_date', models.DateField(blank=True, null=True)),
                ('other_creator', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'ms_project_otherinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MsProjectServerRelation',
            fields=[
                ('rl_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('project_id', models.CharField(blank=True, max_length=256, null=True)),
                ('project_name', models.CharField(blank=True, max_length=256, null=True)),
                ('server_id', models.CharField(blank=True, max_length=256, null=True)),
                ('server_name', models.CharField(blank=True, max_length=256, null=True)),
                ('server_internal_ip', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'ms_project_server_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MsServerList',
            fields=[
                ('server_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('server_name', models.CharField(blank=True, max_length=256, null=True)),
                ('server_hostname', models.CharField(blank=True, max_length=256, null=True)),
                ('server_internal_ip', models.CharField(blank=True, max_length=256, null=True)),
                ('server_external_ip', models.CharField(blank=True, max_length=256, null=True)),
                ('server_os', models.CharField(blank=True, max_length=256, null=True)),
                ('server_memory', models.CharField(blank=True, max_length=256, null=True)),
                ('server_cpu', models.CharField(blank=True, max_length=256, null=True)),
                ('server_disk_capacity', models.CharField(blank=True, max_length=256, null=True)),
                ('server_lx', models.CharField(blank=True, max_length=256, null=True)),
                ('server_purpose', models.CharField(blank=True, max_length=256, null=True)),
                ('server_version', models.CharField(blank=True, max_length=256, null=True)),
                ('server_parent_id', models.CharField(blank=True, max_length=256, null=True)),
                ('server_create_date', models.DateField(blank=True, null=True)),
                ('server_modify_date', models.DateField(blank=True, null=True)),
                ('server_memory_used', models.CharField(blank=True, max_length=256, null=True)),
                ('server_cpu_used', models.CharField(blank=True, max_length=256, null=True)),
                ('server_disk_capacity_used', models.CharField(blank=True, max_length=256, null=True)),
                ('server_remark', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'ms_server_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MsServerMonitorRs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_rs_id', models.CharField(blank=True, max_length=256, null=True)),
                ('m_server_id', models.CharField(blank=True, max_length=256, null=True)),
                ('m_server_name', models.CharField(blank=True, max_length=256, null=True)),
                ('m_server_internal_ip', models.CharField(blank=True, max_length=256, null=True)),
                ('m_open_files', models.CharField(blank=True, max_length=256, null=True)),
                ('m_max_user_processes', models.CharField(blank=True, max_length=256, null=True)),
                ('m_logical_cpu_count', models.CharField(blank=True, max_length=256, null=True)),
                ('m_disk_usages', models.CharField(blank=True, max_length=1024, null=True)),
                ('m_memory_usages', models.CharField(blank=True, max_length=1024, null=True)),
                ('m_version', models.CharField(blank=True, max_length=1024, null=True)),
                ('m_uptime_days', models.CharField(blank=True, max_length=1024, null=True)),
                ('m_load_average', models.CharField(blank=True, db_column='m_load average', max_length=1024, null=True)),
                ('m_rs_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ms_server_monitor_rs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MsUserList',
            fields=[
                ('user_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=256, null=True)),
                ('user_password', models.CharField(blank=True, max_length=256, null=True)),
                ('user_lx', models.CharField(blank=True, max_length=256, null=True)),
                ('super_user_flag', models.CharField(blank=True, max_length=256, null=True)),
                ('server_ip', models.CharField(blank=True, max_length=256, null=True)),
                ('server_name', models.CharField(blank=True, max_length=256, null=True)),
                ('project_name', models.CharField(blank=True, max_length=256, null=True)),
                ('user_sqr', models.CharField(blank=True, max_length=256, null=True)),
                ('user_creator', models.CharField(blank=True, max_length=256, null=True)),
                ('user_create_date', models.DateField(blank=True, null=True)),
                ('user_modify_date', models.DateField(blank=True, null=True)),
                ('user_parent_id', models.CharField(blank=True, max_length=256, null=True)),
                ('web_domain_name', models.CharField(blank=True, max_length=256, null=True)),
                ('web_control_address', models.CharField(blank=True, max_length=256, null=True)),
                ('web_port', models.CharField(blank=True, max_length=256, null=True)),
                ('web_ssl_port', models.CharField(blank=True, max_length=256, null=True)),
                ('web_jvm_memory', models.CharField(blank=True, max_length=256, null=True)),
                ('web_datasource_name', models.CharField(blank=True, max_length=256, null=True)),
                ('web_datasource_user', models.CharField(blank=True, max_length=256, null=True)),
                ('web_datasource_password', models.CharField(blank=True, max_length=256, null=True)),
                ('web_datasource_lx', models.CharField(blank=True, max_length=256, null=True)),
                ('web_datasource_string', models.CharField(blank=True, max_length=256, null=True)),
                ('db_lx', models.CharField(blank=True, max_length=256, null=True)),
                ('db_tablespace', models.CharField(blank=True, max_length=256, null=True)),
                ('db_size', models.CharField(blank=True, max_length=256, null=True)),
                ('remark', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'ms_user_list',
                'managed': False,
            },
        ),
    ]
