# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsUsers',
            fields=[
                ('username', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('cn_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'ms_users',
                'managed': True,
            },
        ),
    ]
